### PR TITLE
Add HEAD request support and body_exists; python test failing

### PR DESCRIPTION
**Pull request by DocSavage**

### CODE REVIEW

**Comment by stuarteberg** [comment]
@DocSavage Does this look okay to you?

**Comment by DocSavage** [comment]
Looks fine but you just stole all my commit lines to libdvid-cpp :)  :100:   Just did that because I discovered the emoticons on github but only know a few of them.

**Comment by stuarteberg** [comment]
>Looks fine but you just stole all my commit lines to libdvid-cpp

If you read the commit messages, I gave you credit, although I guess that won't show up in your github stats.  FWIW, my version of this PR is half as long as yours, so at least I'm getting *less* credit. :-) :beer:

**Comment by DocSavage** [comment]
More seriously, the reason I didn't reuse the make_request is because there's a lot of other settings there  for libcurl that I'm not sure are necessary or even good for pure HEAD requests.  If you think they are necessary, that's fine.

**Comment by stuarteberg** [comment]
>there's a lot of other settings there for libcurl that I'm not sure are necessary or even good for pure HEAD requests.

I don't know if they're necessary, but your tests still pass. My bias is to err on the side of less code, but you know a lot more about http requests than I do.  It's already merged at this point, but if you spot a problem, let me know.

**Comment by DocSavage** [comment]
Yes, my bias is also to err on side of less code *executed*, so when you reuse make_request, the head request will be doing a lot of extraneous logic (e.g., setting write callbacks) compared to my original pull request.  I did bare minimal investigation of libcurl so can't say if it matters.

**Comment by stuarteberg** [comment]
>my bias is also to err on side of less code *executed*

:confused: ... :worried: ... :fearful: ... :scream: ... :boom:

**Pull request merged**
